table 'All measure Tables'
	lineageTag: ecd25098-f8eb-4925-90ae-ad976288ccef

	measure Sales = SUM('Orders Details'[Total Sales])
		formatString: \$#,0.0000;(\$#,0.0000);\$#,0.0000
		lineageTag: f1ced7c8-0ff1-4b4e-a7e6-1eb698f1b539

	measure 'Total Orders' = COUNT('Orders Details'[OrderID])
		formatString: 0
		lineageTag: 14737659-b109-42c3-85e3-5e29dc1dcada

	measure 'Distinct Orders' = DISTINCTCOUNT('Orders Details'[OrderID])
		formatString: 0
		lineageTag: a598a6a0-c85d-4b35-a087-826c1f512fbf

	measure 'Total Customer' = DISTINCTCOUNT(Customers[CustomerID])
		formatString: 0
		lineageTag: fe43c910-5d03-4c92-8293-6d06bd82ca3e

	measure 'Unique Product' = DISTINCTCOUNT('Orders Details'[ProductID])
		formatString: 0
		lineageTag: 37953f85-8019-4915-a982-e58a2a9e2cb5

	measure 'Total Employee' = DISTINCTCOUNT(Orders[EmployeeID])
		formatString: 0
		lineageTag: a7c95e23-9fda-488b-a3bc-8943baaaff9e

	measure 'Total Supplier' = DISTINCTCOUNT('Product'[SupplierID])
		formatString: 0
		lineageTag: aca98a3d-b673-49f0-894d-35afaa434e2a

	measure 'Total Shippers' = DISTINCTCOUNT(Orders[ShipVia])
		formatString: 0
		lineageTag: 75afdf16-c663-410c-a10d-7b1ae8619cbd

	measure 'Category Type' = DISTINCTCOUNT('Product'[CategoryID])
		formatString: 0
		lineageTag: c618d482-9ee7-4b4d-887a-60f487cedd41

	measure 'Average Order Value (AOV)' = DIVIDE([Sales], [Total Orders])
		lineageTag: cf8df372-6164-4070-8faa-f76d57a205ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TopSellingProduct = ```
			
			CALCULATE(
			    VALUES('Product'[ProductName]),
			    TOPN(
			        1,
			        'Product',
			        CALCULATE(SUM('Orders Details'[Total Sales])),
			        DESC
			    )
			)
			
			```
		lineageTag: e4583de6-66ed-439e-8ead-f1ff84ed799e

	measure OnTimeDeliveryRate =
			
			DIVIDE (
			    SUMX (
			        'Orders',
			        IF (
			            'Orders'[ShippedDate] <= 'Orders'[RequiredDate],
			            1,
			            0
			        )
			    ),
			    COUNTROWS('Orders')
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5120bcb3-52c5-4638-8e1e-db92c64e6ae8

	measure YoYSales = ```
			
			CALCULATE(
			    [Sales],
			    SAMEPERIODLASTYEAR('Fin-Calendar'[Date])
			)
			
			```
		lineageTag: 84c97d32-d50b-49ad-a429-e40698620075

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MoMSales = ```
			
			CALCULATE(
			    [Sales],
			    DATEADD('Fin-Calendar'[Date], -1, MONTH)
			)
			
			```
		lineageTag: 711ec61f-bb0c-4702-86a7-6c28253eee37

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure QoQSales = ```
			
			CALCULATE(
			    [Sales],
			    DATEADD('Fin-Calendar'[Date], -1, QUARTER)
			)
			
			```
		lineageTag: 4f54eb6a-b4f7-4d48-bd05-da336ef02068

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YoYGrowth = ```
			
			DIVIDE(
			    [Sales] - [YoYSales],
			    [YoYSales],
			    0
			)
			
			```
		lineageTag: dd2913b0-cb6a-42d2-ba60-0f2fc6597866

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MoMGrowth = ```
			
			DIVIDE(
			    [Sales] - [MoMSales],
			    [MoMSales],
			    0
			)
			
			```
		lineageTag: f778632e-240c-4925-bcc1-bb65c3ba0a74

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure QoQGrowth = ```
			
			DIVIDE(
			    [Sales] - [QoQSales],
			    [QoQSales],
			    0
			)
			
			```
		lineageTag: 4c145f87-92c8-42b7-aa80-97d953c23829

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ProductsToReorder = ```
			
			CALCULATE(
			    COUNTROWS('Product'),
			    'Product'[UnitsInStock] <= 'Product'[ReorderLevel]
			)
			
			```
		formatString: 0
		lineageTag: ed5c8a09-ea1b-49ee-bc30-934d9ead3ded

	measure PctProductsToReorder =
			
			DIVIDE(
			    [ProductsToReorder],
			    COUNTROWS('Product'),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e9fc5ba9-a7b3-4397-8578-ad479b42cb0b

	measure UnitsToReorder = ```
			
			SUMX(
			    'Product',
			    IF(
			        'Product'[UnitsInStock] <= 'Product'[ReorderLevel],
			        'Product'[ReorderLevel] - 'Product'[UnitsInStock],
			        0
			    )
			)
			
			```
		formatString: 0
		lineageTag: 0fe45ebc-edb4-4043-80eb-f7b680f9ba93

	column Column1
		dataType: string
		lineageTag: 1720c8b5-d0be-41ee-8122-f9fdc861478a
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition 'All measure Tables' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

