table Customers
	lineageTag: 1a298af0-6766-4d63-8d50-8de1efe9b121

	column CustomerID
		dataType: string
		lineageTag: daba190e-1832-4c8d-8ea1-5df761452432
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CompanyName
		dataType: string
		lineageTag: d9de046c-b653-48bf-bcd1-cc481cc0b2b2
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column ContactName
		dataType: string
		lineageTag: d57bf8f0-1bb6-49e6-acbb-75c5a902ecff
		summarizeBy: none
		sourceColumn: ContactName

		annotation SummarizationSetBy = Automatic

	column ContactTitle
		dataType: string
		lineageTag: b4745a4d-e1f0-490b-9d6f-c873f566ace5
		summarizeBy: none
		sourceColumn: ContactTitle

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 5e52db18-8278-4751-a5bc-8570ecd46b01
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 64bdca9b-b27d-474b-93fa-a0f7ba26f364
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b73fc2d6-844c-4b42-82b8-7758b7e365be
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		lineageTag: a1f4290a-e589-4b18-9da2-089ba1922a83
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: d347342a-858d-436c-92ff-a4f1c764d97c
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: fed4f9d2-612a-4c36-afef-d0b29a387ebe
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Fax
		dataType: string
		lineageTag: fb087880-4060-429d-8824-1b236c3cfe81
		summarizeBy: none
		sourceColumn: Fax

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Pawan Kataria\Downloads\Northwind.xlsx"), null, true),
				    Customers_Sheet = Source{[Item="Customers",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Customers_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerID", type text}, {"CompanyName", type text}, {"ContactName", type text}, {"ContactTitle", type text}, {"Address", type text}, {"City", type text}, {"Region", type text}, {"PostalCode", type text}, {"Country", type text}, {"Phone", type text}, {"Fax", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

