table Product
	lineageTag: 758fe429-81c7-4795-b0ae-4046b3dbeb3c

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 62e1f3c5-7e47-4fd9-8a98-061a5cf2e94f
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: bd8976d2-317b-4a54-b5dc-b71d409d7048
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column SupplierID
		dataType: int64
		formatString: 0
		lineageTag: e934930e-4643-4747-8226-7ea5bc89bf50
		summarizeBy: none
		sourceColumn: SupplierID

		annotation SummarizationSetBy = Automatic

	column CategoryID
		dataType: int64
		formatString: 0
		lineageTag: e1544ea3-f117-4d80-97e9-faece93490d8
		summarizeBy: none
		sourceColumn: CategoryID

		annotation SummarizationSetBy = Automatic

	column QuantityPerUnit
		dataType: string
		lineageTag: 888d83a9-4902-4cd4-9158-a29baddf664b
		summarizeBy: none
		sourceColumn: QuantityPerUnit

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: c36e6538-7cd3-4fb4-8756-afbdd81ccbaf
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitsInStock
		dataType: int64
		formatString: 0
		lineageTag: 724f36e2-2c2b-4175-967d-8e08b913e5c6
		summarizeBy: sum
		sourceColumn: UnitsInStock

		annotation SummarizationSetBy = Automatic

	column UnitsOnOrder
		dataType: int64
		formatString: 0
		lineageTag: 51da8d3f-5139-4557-b2d2-3c1aa82f5b77
		summarizeBy: sum
		sourceColumn: UnitsOnOrder

		annotation SummarizationSetBy = Automatic

	column ReorderLevel
		dataType: int64
		formatString: 0
		lineageTag: 2864ddb2-c19d-4858-ba8f-68831193474f
		summarizeBy: sum
		sourceColumn: ReorderLevel

		annotation SummarizationSetBy = Automatic

	column Discontinued
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4daf603b-ae17-4552-a7e0-c0bb7df569fb
		summarizeBy: none
		sourceColumn: Discontinued

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 5fdddf0d-2209-48f3-9417-ab65516b4436
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	column CompanyName
		dataType: string
		lineageTag: 2d48203a-773e-4669-9a6c-a5a9380c2d1c
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column StockStatus = ```
			
			IF(
			    'Product'[UnitsInStock] <= 'Product'[ReorderLevel],
			    "Reorder",
			    "Sufficient"
			)
			
			```
		lineageTag: 7934ea82-b663-46f0-ace5-abc0b28735f2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TotalUnitsAvailable = 'Product'[UnitsInStock] +'Product'[UnitsOnOrder]
		formatString: 0
		lineageTag: c5dd16c3-aa30-492f-bd3d-0469b56c4324
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Pawan Kataria\Downloads\Northwind.xlsx"), null, true),
				    Product_Sheet = Source{[Item="Product",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Product_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", Int64.Type}, {"ProductName", type text}, {"SupplierID", Int64.Type}, {"CategoryID", Int64.Type}, {"QuantityPerUnit", type text}, {"UnitPrice", type number}, {"UnitsInStock", Int64.Type}, {"UnitsOnOrder", Int64.Type}, {"ReorderLevel", Int64.Type}, {"Discontinued", type logical}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"CategoryID"}, Categories, {"CategoryID"}, "Categories", JoinKind.LeftOuter),
				    #"Expanded Categories" = Table.ExpandTableColumn(#"Merged Queries", "Categories", {"CategoryName"}, {"CategoryName"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Categories", {"SupplierID"}, Suppliers, {"SupplierID"}, "Suppliers", JoinKind.LeftOuter),
				    #"Expanded Suppliers" = Table.ExpandTableColumn(#"Merged Queries1", "Suppliers", {"CompanyName"}, {"CompanyName"})
				in
				    #"Expanded Suppliers"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

